apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: golang-build
spec:
  inputs:
    resources:
    - name: qotd-git
      targetPath: /
      type: git
  outputs:
    resources:
    - name: qotd-image
      targetPath: qotd:v1
      type: image
  steps:
  - name: build
    image: golang:latest
    command:
    - go 
    args:
    - build